[package]
name = "vdev-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vdev-app"
path = "src/main.rs"

[build-dependencies]
slint-build = "1.13"
slint-pixel = { git = "https://github.com/gqf2008/slint-pixel" }

[dependencies]
slint = "1.13"
slint-pixel = { git = "https://github.com/gqf2008/slint-pixel" }
anyhow = "1.0.104"
vdev-screen = { path = "../vdev-screen" }
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", features = ["NSString", "NSURL", "NSArray", "NSDictionary", "NSValue"] }
objc2-app-kit = { version = "0.3.2", features = ["NSWorkspace", "NSApplication"] }
objc2-av-foundation = { version = "0.3.2", features = ["AVCaptureDevice", "AVMediaFormat"] }
objc2-core-foundation = "0.3.2"
