use std::error::Error;

use vergen_gix::{Emitter, GixBuilder};

fn main() -> Result<(), Box<dyn Error>> {
    let mut winres = winres::WindowsResource::new();

    // winres 的注册表探测在某些环境会拿到空 KitsRoot10（`\bin\x64\rc.exe`），
    // 这里显式读取注册表并设置 SDK 根目录
    {
        use winreg::enums::HKEY_LOCAL_MACHINE;
        use winreg::RegKey;
        let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
        let kits_root: String = hklm
            .open_subkey(r"SOFTWARE\Microsoft\Windows Kits\Installed Roots")?
            .get_value("KitsRoot10")?;
        // 优先用带版本号的 bin 目录（bin\x64\rc.exe 只是转发器，可能找不到依赖）
        let kits_bin = std::path::Path::new(&kits_root).join("bin");
        let rc_dir = std::fs::read_dir(&kits_bin).ok().and_then(|entries| {
            entries
                .filter_map(Result::ok)
                .map(|e| e.path())
                .filter(|p| p.is_dir() && p.join("x64").join("rc.exe").is_file())
                .max()
        });
        if let Some(dir) = rc_dir {
            winres.set_toolkit_path(&dir.join("x64").to_string_lossy());
        } else {
            winres.set_toolkit_path(&kits_root);
        }
    }

    // as much as I don't like setting this here, because it belongs to the logger crate
    // I want my own resource info for this crate. There's a linker error unless we do it
    // all in one fell swoop. This is the only option for now
    //
    // For location of the content, see winlog/res/eventmsgs.rc
    winres
        .append_rc_content(
            r#"
/* Do not edit this file manually.
This file is autogenerated by windmc.  */


// Country: United States
// Language: English
#pragma code_page(437)
LANGUAGE 0x9, 0x1
1 MESSAGETABLE "res/MSG00409.bin"
    "#,
        )
        .compile()
        .unwrap();

    // need linked c runtime for umdf includes
    println!("cargo::rustc-link-lib=static=ucrt");
    //println!("cargo:rustc-link-lib=static=vcruntime");

    println!("cargo::rerun-if-changed=build.rs");

    // emit vergen build instructions
    Emitter::default()
        .add_instructions(&GixBuilder::all_git()?)?
        .emit()?;

    Ok(())
}
