use std::error::Error;

use vergen_gix::{Emitter, GixBuilder};

fn main() -> Result<(), Box<dyn Error>> {
    // minor(f)：winreg / winres 只服务于「Windows 宿主」的 SDK 注册表探测与资源段编译。
    // - winreg 0.52 在非 Windows 宿主直接 compile_error!（其 src/lib.rs:115），
    //   因此 Cargo.toml 已把它移入 [target.'cfg(windows)'.build-dependencies]；
    //   注意 target 门控针对的是「目标平台」，而 build.rs 代码按「宿主平台」编译，
    //   所以这里的引用代码必须用 #[cfg(windows)]（宿主判定）整体门控，
    //   macOS 宿主交叉编译时该块不参与编译，build.rs 其余部分照常执行。
    // - CARGO_CFG_WINDOWS（运行时 env）表达的是「目标平台」，不能用来门控
    //   依赖本身的编译，仅可表达目标语义，故此处不采用。
    #[cfg(windows)]
    {
        let mut winres = winres::WindowsResource::new();

        // winres 的注册表探测在某些环境会拿到空 KitsRoot10（`\bin\x64\rc.exe`），
        // 这里显式读取注册表并设置 SDK 根目录
        {
            use winreg::enums::HKEY_LOCAL_MACHINE;
            use winreg::RegKey;
            let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
            let kits_root: String = hklm
                .open_subkey(r"SOFTWARE\Microsoft\Windows Kits\Installed Roots")?
                .get_value("KitsRoot10")?;
            // 优先用带版本号的 bin 目录（bin\x64\rc.exe 只是转发器，可能找不到依赖）
            let kits_bin = std::path::Path::new(&kits_root).join("bin");
            let rc_dir = std::fs::read_dir(&kits_bin).ok().and_then(|entries| {
                entries
                    .filter_map(Result::ok)
                    .map(|e| e.path())
                    .filter(|p| p.is_dir() && p.join("x64").join("rc.exe").is_file())
                    .max()
            });
            if let Some(dir) = rc_dir {
                winres.set_toolkit_path(&dir.join("x64").to_string_lossy());
            } else {
                winres.set_toolkit_path(&kits_root);
            }
        }

        // as much as I don't like setting this here, because it belongs to the logger crate
        // I want my own resource info for this crate. There's a linker error unless we do it
        // all in one fell swoop. This is the only option for now
        //
        // For location of the content, see winlog/res/eventmsgs.rc
        winres
            .append_rc_content(
                r#"
/* Do not edit this file manually.
This file is autogenerated by windmc.  */


// Country: United States
// Language: English
#pragma code_page(437)
LANGUAGE 0x9, 0x1
1 MESSAGETABLE "res/MSG00409.bin"
    "#,
            )
            .compile()
            .unwrap();
    }

    #[cfg(not(windows))]
    {
        // 非 Windows 宿主（macOS 交叉编译）：跳过资源段编译与 SDK 注册表探测。
        // 代价：产物缺消息表资源（事件日志查看器无法格式化消息），不影响编译与链接；
        // 正式 Windows 宿主构建走上面的完整路径。
        println!("cargo:warning=non-Windows host: skipping Windows resource compilation");
    }

    // need linked c runtime for umdf includes
    println!("cargo::rustc-link-lib=static=ucrt");
    //println!("cargo:rustc-link-lib=static=vcruntime");

    println!("cargo::rerun-if-changed=build.rs");

    // minor(e)：无 .git（源码包/浅检出）时的降级。
    // 实测（vergen-gix 1.0.9，fail_on_error 默认 false）：缺 git 时 emit() 返回 Ok，
    // 并以 "VERGEN_IDEMPOTENT_OUTPUT" 占位值 + cargo:warning 提示（2026-09 实测），
    // entry.rs 的 env!("VERGEN_GIT_SHA") 因此总能解析。这里再加一层显式兜底：
    // emit 若意外失败则写占位 VERGEN_GIT_SHA，保证编译不因缺 git 而中断。
    if let Err(e) = Emitter::default()
        .add_instructions(&GixBuilder::all_git()?)?
        .emit()
    {
        println!("cargo:warning=vergen emit failed, falling back to placeholder: {e}");
        println!("cargo::rustc-env=VERGEN_GIT_SHA=unknown");
    }

    Ok(())
}
